### ISSUE TITLE
Add Font Type option to "addtext"

### ISSUE THREAD

**Issue by stefslon** [stefslon/exportToPPTX#20]
See title.

**Comment by stefslon** [comment]
Added.

**Comment by bdoch** [comment]
We are unable to determine how to change the font Type using your latest version. Please provide an example showing how to change the font type using 'addtext' command. 

Thanks!

**Comment by stefslon** [comment]
In `addtext` command use 'FontName','Some Font Name' property-value pair. I am going to update README and example files with some more details.
