### ISSUE TITLE
The new R2014b graphical changes cause a crash of your script

### ISSUE THREAD

**Issue by thegodone** [stefslon/exportToPPTX#21]
Error using exportToPPTX>addPicture (line 1225)
addPicture command requires a valid figure/axes handle or filename or CDATA

Error in exportToPPTX (line 372)
            PPTXInfo    = addPicture(PPTXInfo,imgData,varargin{3:end});

**Comment by ScienceMinded** [comment]
I have experience the same problem with R2014b.  It appears that gcf is unrecognized or not valid.  Any fixes to this problem yet, or work arounds??  Please help!!

**Comment by stefslon** [comment]
Unfortunately I don't have access to the new MatLab. Not yet anyway. So if anyone has a fix I will gladly roll it in.

**Comment by stefslon** [comment]
thegodone, ScienceMinded, I have just commited an update. Please see if it fixed this issue. This update is done part by reading about changes in new MatLab, part by running older MatLab with -hgVersion 2 flag. Hope this resolves the issue.

**Comment by stefslon** [comment]
Ran tests with MatLab 2015a and everything works fine now.
