### ISSUE TITLE
Adding a slide directly before the last slide of a PPTX doesn't work

### ISSUE THREAD

**Issue by bdoch** [stefslon/exportToPPTX#22]
If an existing PowerPoint presentation contains 5 slides, and the exportToPPTX 'addslide' option is called with slide number set to '5', the slide is added to slide position 6.  

If an existing PowerPoint presentation contains 5 slides, and the exportToPPTX 'addslide' option is called with slide number set to '4', the slide is added to slide position 4.

The goal is to insert a slide directly before the last slide of the presentation.

**Comment by stefslon** [comment]
Fixed. Thanks!
