### ISSUE TITLE
Add ability to add content to an existing slide

### ISSUE THREAD

**Issue by bdoch** [stefslon/exportToPPTX#23]
'Addpicture', 'addnote', 'addtext', 'addshape' and 'addtable'  all add content to the current slide. Suggest adding an input option to specify a slide number instead of using current slide. This would allow the user to add content to an existing slide.

Appreciate the function!

**Comment by stefslon** [comment]
bdoch, I added this feature. I've done some preliminary testing and it seems to work well. Please let me know if you hit any issues. Thanks.

**Comment by bdoch** [comment]
Have done some initial testing using 'switchslide' command and have found a few problems.

After opening several different pptx files and executing the following commands:
exportToPPTX('switchslide',sldID);
exportToPPTX('addtext',...);

We noticed three possible results:  
1) Function crashes at Line 2233 b/c the 'objId' field is empty for PPTXInfo.currentSlide
2) Function executed without error, but when attempting to open newly created pptx file, PowerPoint displayed an error saying there was corrupt data and it inserted a blank slide instead of the textbox.
3) Function executed without error, and generated the textbox correctly, however it placed it on [sldID - 1] instead of on sldID.

Thanks.

**Comment by stefslon** [comment]
> We noticed three possible results:
> 1) Function crashes at Line 2233 b/c the 'objId' field is empty for PPTXInfo.currentSlide
> 2) Function executed without error, but when attempting to open newly created pptx file, PowerPoint displayed an error saying there was corrupt data and it inserted a blank slide instead of the textbox.
> 3) Function executed without error, and generated the textbox correctly, however it placed it on [sldID - 1] instead of on sldID.

I wasn't able to recreate all of these errors, but I was able to get the first one at least. I think these issues might be coming from the same code bug, which I fixed with the latest commit.

**Comment by bdoch** [comment]
Thanks for the fix, tested your latest code, seems to work well, can now add content to existing slides.

**Comment by stefslon** [comment]
Thanks.
