### ISSUE TITLE
Addtext does not allow 'Position' at the beginning of the text string

### ISSUE THREAD

**Issue by bdoch** [stefslon/exportToPPTX#25]
The following statement will result in a warning:

exportToPPTX('addtext','Position Test','Position',[0 0.6 10 0.5])

If the text string that follows 'addtext' begins with the string 'Position', a warning is generated.

Thanks,
Bruce

**Comment by stefslon** [comment]
Good catch! I will fix this as soon as I get a chance. Thanks.

**Comment by stefslon** [comment]
This issue was also affecting addtable command. Should be fixed now.
