### ISSUE TITLE
Background Color for 'addtable' command does not work

### ISSUE THREAD

**Issue by sohaibmaalik** [stefslon/exportToPPTX#26]
Hi,

Excellent work you have done which helped me a lot in generating measurement reports via Matlab. I am struggling with 'addtable' command. I want to change the background color of the table i have created but it does not work as it is for 'addtext' command. For example;

exportToPPTX('addtable',tableData,'Position',[sm_xbm sm_ybm sm_wbm sm_hbm],...
              'Vert','middle','Horiz','center','FontSize',8,'FontWeight','bold',...
             'BackgroundColor','c','ColumnWidth',[0.6 0.4]);

It generates table according to the passed data and mentioned settings but it does nothing to the background color at all. Am i doing anything wrong ? When i use the ** 'BackgroundColor','c', ** together with 'addtext' command it works like a charm. But not with 'addtable' command, even though it has been mentioned that all additional options of 'addtext' command works with 'addtable' as well. Any Comment ?

/Sohaib

**Comment by stefslon** [comment]
Turns out 'BackgroundColor' property check was missing from addtable command. I have added it now.
