### ISSUE TITLE
parens in ** markup

### ISSUE THREAD

**Issue by eikceb** [stefslon/exportToPPTX#30]
Putting a parenthesis in markdownseems to void the markup.  For example, I'm inputting a table where one of the cells is supposed to be bolded **Latency (s)**.  The markdown just shows up as *\* and does not bold the text

**Comment by gknor** [comment]
I've faced similar problem with minus sign (e.g. '\**-1**'). You have to change line 870, from:
`[fmtStart,fmtStop,tokStr,splitStr] = regexpi(addParaText,'\<(*{2}|*{1}|_{1})([ ,:.\w]+)(?=\1)\1\>','start','end','tokens','split');`
to:
`[fmtStart,fmtStop,tokStr,splitStr] = regexpi(addParaText,'\<(*{2}|*{1}|_{1})([()\- ,:.\w]+)(?=\1)\1\>','start','end','tokens','split');`
I've added ()\- in proper place.

**Comment by gknor** [comment]
@stefslon I've tried to pull request, but GitHub Desktop tells that "Sync failed to push local changes. It seems you do not have permission to push you changes to this repository."

**Comment by stefslon** [comment]
@gknor I finally got around to pushing your change in.
