### ISSUE TITLE
Convert to a Object Oriented Design

### ISSUE THREAD

**Issue by curtisma** [stefslon/exportToPPTX#33]
It seems like converting the code to an object oriented design would make it easier to use and cleaner.  The current file has almost 3000 lines of code!  It would also enable the user to have multiple presentations edited at the same time.  

It seems like it would be pretty straightforward to make the conversion with each of the commands converted to methods of the class and the fields of PPTXInfo would become properties of the class.  The other local helper functions would be converted to methods with restricted access.  

Converting the current function to a single class in this way would be a good start but eventually it would be good to split some of the parts of the ppt presentation into different classes.  For example we would add a class for a slide and the main presentation slide would contain an instance of the slide class for each slide in the presentation.

**Comment by stefslon** [comment]
@curtisma that's something that has been on my todo list for a while. It turned out simpler than I thought. I've checked in my first attempt on [class-implementation branch](/stefslon/exportToPPTX/tree/class-implementation).

**Comment by stefslon** [comment]
Class-based/Object Oriented design is now in the main branch (#38).

**Comment by curtisma** [comment]
Awesome!
