### ISSUE TITLE
Escaping markdown characters

### ISSUE THREAD

**Issue by mjc865** [stefslon/exportToPPTX#34]
Is there any way to escape text markdown characters? I need to have some special characters (specifically, asterisks) show up in a paragraph, without having it interpreted as markdown.

**Comment by stefslon** [comment]
@mjc865 I made some changes to markdown parsing. If there is a space after formatting character (* or ** or _) it won't treat it as markdown. If this is not enough, I've also added 'markdown' property, that you can set to false to disable markdown parsing. See examples_exportToPPTX.m for usage.

**Comment by mjc865** [comment]
@stefslon Thank you so much for the quick response - that'll work for what I need, since I can just disable markdown for the entire text box. 

In the future, it might be helpful to define an escape character (maybe a caret [^]?) so that the user is not forced to either include a space after their symbols, or disable markdown for the entire text box. 

For example, I need to include a string that looks like this in my presentation:

1**, 2**, 3**, 4**

Currently, I either have to include additional spaces to make it work:

1** , 2** , 3** , 4**

Or disable markdown for the entire textbox containing that. If I can escape with a caret, I can ask exportToPPTX to add the string: '1^**, 2^**, 3^**, 4^**' and it would print as intended. 

There's probably a fancy regex query you could use for this, or you could look at the tokens containing the identified markdown characters and just check to see if they are preceded by a caret, and remove them from the list if so. Might need an additional step to make sure that users can still print a caret (probably by escaping that with an additional caret) depending on the implementation.

The fix you put in place will work for me though - thank you so much! Also, you might want to update the Help on the function so that it mentions how to disable text markdown.

**Comment by stefslon** [comment]
@mjc865 I've added markdown escaping using backslash character. This seems to be the standard escape character in markdown.

Also I misspoke, markdown character has to be followed by an alphanumeric [a-z0-9] character to be treated as markdown. In your example with commas exportToPPTX will not interpret those asterisks as formatting commands.
