### ISSUE TITLE
addtext add lists

### ISSUE THREAD

**Issue by NimosSereth** [stefslon/exportToPPTX#36]
hey, your code is working great, but I can't figure out how to add a list with with lets say 9 words into a textbox.

**Comment by stefslon** [comment]
Break your text into a cell array and have each cell array entry start with "- " (dash space):
```
exportToPPTX('addtext', ...
    {'Bulleted items:', ...
    '- Each bulleted line must start with a "-" symbol', ...
    '- Use cell arrays to add multiple lines of text', ...
    '- Last item is a very, very, very, very, very long one, so that when the text wraps to the new line a proper hanging line can be observed.', ...
    '-Last item does not have a space between the hyphen and the text so it does not become a list item.'});
```

**Comment by NimosSereth** [comment]
Oh thanks alot, it worked very well! 

Can I also add results / variables which I calculated in my program? 
I want it to look somewhat like this: 
![example](https://user-images.githubusercontent.com/42576967/44646566-bf775180-a9db-11e8-96d1-4f5e4f65c773.PNG

so I can write the measure (result of calculation) and unit of measure (fixed text).

Thanks in advance!
