### ISSUE TITLE
Corrupt PPTX after setting 'LineWidth' = 0 in the function addTableCell.

### ISSUE THREAD

**Issue by MasseyGhalayani** [stefslon/exportToPPTX#43]
I wanted to remove the border of my table which as I go through the functions in the script, I found out if we set LineWidth in the function addTableCell to any value the pptx get corrupted.

**Comment by stefslon** [comment]
Thanks for reporting this. There was an issue with table's default edge color being invalid. I've added a test case to examples_exportToPPTX.m and resulting PPTX file is no longer corrupted.
